// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic dimensions + blur placeholders for every product photograph.

export type ProductImage = {
  src: string
  width: number
  height: number
  blurDataURL: string
}

export const productImages = {
  'box-open': {
    src: '/images/box-open.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRhgBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSIoAAAANuTJE9D80cBtJkuT8pP/OEv9PI3LQcqGpslCrDsaAHT1iAibg4o19682LV2M+u1L43qXx/+Hd2SmkayNjjCw4e+69550F9KMuYR1eNMI9Sn9GiVtkb36NWN0QgXACCIgjfkSNlzomaiNBC1CzojgokVJoNESKLbcYTHfKrkk/SNWufaQ4mT6g9CRWUDggaAAAAFAEAJ0BKgwAEgA+wU6hSqekIyGwCADwGAlqAJ0ygANOmBtCf3r/r0KWjAAA/u6JLT4qzxbjTKDX0HIlXrZBv2Xqt1y//td31VBNV2o31bz39WmUHjviL/07knhTKeu8qFFX9K13gAAA',
  },
  'fist-angle': {
    src: '/images/fist-angle.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRj4BAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSJYAAAANuTJE9D80cBxJcuQcNcH//1Nr6fIJ2VTWFGrsRq+7OGERmHWJiAnIVT6+R/v0YrzRAUEeOzQe3RtH1sCyyK290gmQxROf+3rnwEsb/etMF0Jh6av3eACUQ0VVAYsRjgDIPqiMWhLSGZmugnVV8zr1p1DWM1dO9lAR84W+Zlq7+J9/TvXI6XfXiJE7m69bayq+VJ7HtQRWUDggggAAABAEAJ0BKgwAEgA+wU6gSqekIyGwCADwGAlsAJ0ygxgDRKFhbqPwbTfAAPQDn4DTx+58mMorZ20Sfz8xHy8+1pp5vHrIfXpWpzJCEHJxu09VJV1Yc9+FxGp1n0IdG611r4EDXFKyfT0Z0rs5nUwtFrIdrG1wddNLMWj3jTM3EUMgwAA=',
  },
  'fist-back': {
    src: '/images/fist-back.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRkQBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSJAAAAANuTJE9D80cBxJdt3QE+T9L0p4r1wn6AeaiItV5Bbz04eXynwTCRETkL28Tt8QL44uGAhgpK73fIuxs4LFNTzlHBOATuytXshuoGcwN3UtWRk9N5iprtgaEO5uEXIwFQ6EHKBc/0TxVALCQ2YiCaRkdX39kyDlv5X6ca1ygr8lr7tSX78N5LW5sxOAVQHv/wFWUDggjgAAAJAEAJ0BKgwAEgA+wU6hSqekIyGwCADwGAlsAJ0ygtQHqqjknGsvpLIONLqSQAD2NB8z+iISoqaCWk3Yu6HSTnol1aH9vJaWm3t68B1Rr3bxoQk36Q0Fclyy5n7dj6NiYCH3K3wcsQUPxIX1rQQA8h4y7LJCTuiYghiWxS+RSeKYxocik8QMKrSlOaegAAA=',
  },
  'fist-beside-box': {
    src: '/images/fist-beside-box.webp',
    width: 2000,
    height: 1333,
    blurDataURL:
      'data:image/webp;base64,UklGRrwAAABXRUJQVlA4WAoAAAAQAAAACwAABwAAQUxQSFwAAAANuTJE9D/gOJIkqek5Qbf895AXT2knmB43IiYg8ObraTkcTuLlxQFdCrmXt59TSdDaMOGutTIAWrmEINJfagOIBDiAGyUWICqOkrkBRUALiZ1LarQCNMiAgCQKAFZQOCA6AAAA0AEAnQEqDAAIAALASCWwAnQAxs0p1AAA/qKJQryOy3KJekpWt35vX2wD4N+eTznJt+OxjG2aqAAAAA==',
  },
  'fist-front': {
    src: '/images/fist-front.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRjwBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSJAAAAANuTJE9D80cBTJdu18/wXa/0K9934JffjpG85LdTgvElxOKrgvFRETMAGLfP+S1nhwx1YiIHbqybUrlnsJtRX3bvUbG1WQPHJqogN2ieoXjqn+oBnVxjECILOy3ABKXZ7De8wpmVUhYULuAaRbU4W5Q2snppgOY3Oytag4jDYkPjCr248E0hHs/9cFKDUzdABWUDgghgAAANADAJ0BKgwAEgA+wU6gSqekIyGwCADwGAlsAJ0vUZQAglQ5ZwVYAAD0A9Gy0tXzVkzKsj6fGPToklUA7WhizKfoOp7otYCMn/0fJK4/WNqeY+Tk8YXM2EDbV7U5uY3rJVcW7lf7BNRXIKlXEMerl9o8bFuqJ/wadFnygXun/Bp0WfEtUoAA',
  },
  'fist-on-box': {
    src: '/images/fist-on-box.webp',
    width: 2000,
    height: 1333,
    blurDataURL:
      'data:image/webp;base64,UklGRroAAABXRUJQVlA4WAoAAAAQAAAACwAABwAAQUxQSFUAAAANuS5E9D/gOpLdtjkkiV/qv87sBMCpiIgJmAACblCbFYYAAEKgNQj8TSgX9SOcKQ8ISEnBzMxDae6SwgAI9fJk1Km1gnRKd0lMFnfFIN09XAJCWFwAAFZQOCA+AAAA8AEAnQEqDAAIAALASCWYAnQBA/es2LNAAP7xoPfFgyckveC1Tm6WDXEdE1Y3mVnzmGiJitTKtjKHWcoAAAA=',
  },
  'fist-profile': {
    src: '/images/fist-profile.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRigBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSIcAAAANuTJE9D80kBxJUiQNL/7/n8zMT/DUMoTy3KHs66ge0H2PmIAJmOT1p2Z849IFPPdg6a0O7dGGawb7bahz6RUg60prbyQF2a0Xtm0xAjLLfbUBQCIs8dAiKZBBSuEh3gBEinICCqXlAIjqzrjva10Q34z6HAcBUTEadQBub3Fs178etLcxxEMAVlA4IHoAAADwAwCdASoMABIAPsFOoEqnpCMhsAgA8BgJbACdMoMYNcwAnWcRtbZAAP4fMp6tbziEpbhwVuEqGMOxU67HZe7Y2G0UGHN+9WeIC59WqCnr9rDS4ZI0buWkFIPYfLNbk2D74K1IRsH3wJXDcMv/kurQn6e/5Lq0J4AAAA==',
  },
  'fist-side': {
    src: '/images/fist-side.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRjgBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSIwAAAANuTJE9D80cBtJciQdZzj/vaTPOZXeg1yMeoVedRr1Kldv9IgJmIBBPnAIPQkhQCNTce/Og/JMoJmJuHaF1oBEqhtIQDyKWJhL00HUr7Gl/z4rELb4aa0D0gr/SLwrCcZNoHRIdoIIEiwDuDv9lDgBjnrhc2VNrRpu7f2U0pcbAh+dGaoJ8NPr63gJAVZQOCCGAAAA0AQAnQEqDAASAD7BTqBKp6QjIbAIAPAYCWoAnTKDILk/+gCgABbAAtnhsL8PIAAA/sD8zGrcBHQzF6zpOoCUVY8v+iLYHlTX6CsvI/g8y538G0gRvOkyp4ww61c7V+21wWf+DXIrIhYF2CqKhh9v4WZdzXisSW4j/0JUdhRwCMQXOIMAAAA=',
  },
  'fist-top': {
    src: '/images/fist-top.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRmgBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSJ8AAAANuTJE9D80kBQIUiSNr/z/o+5y3C9EMS5JnivJdUvoaxbMaYmYgOzlmT6RB49gABixdqvcuNfKEGaHypNLJzImHAtKIpI+hmuqHDuiJZWMa9M2xe+ko1ciOlc6/wUSoWDuSFgtdiCdwFzI6VSyBkyb/k+b/SKIipId+6ZQfvMrdLq3itd3mcZ0+vL7he9cMJ/6OSCmplVzJSAerfjuCwAAVlA4IKIAAABwBACdASoMABIAPsFOoEqnpCMhsAgA8BgJbACdGaAwTPJAP0AAiPfIaFMDAAD0RfiieLVXqoAJDB0Xn41hnuhiNj7XZ2QVGC5b4bbAdz+7Ky4x8IqJkGvk9GzVD3bJXZgogFS+G5cgXtaJiYOjv37N//9IipNwu45GEp3szdUT6Tt3wA9c/dn2wW79s/gywyh/Djp/x39Y3DJekgxN+lAAAAA=',
  },
  'full-set': {
    src: '/images/full-set.webp',
    width: 1333,
    height: 2000,
    blurDataURL:
      'data:image/webp;base64,UklGRjYBAABXRUJQVlA4WAoAAAAQAAAACwAAEQAAQUxQSKYAAAANuTJE9D80cBzQbd24d3v0/Q/Yu51eptzgCUxPCP5VBD0FEAhklfaICZiAWrxkHd/DHRgDaPIGuybJ9FmH37py4ywos2ZzcED0lrZwslEGeqoD+i3uazML7+9ESUTFTIhVS0wJfSPFCYwSVMc4BkMFdrV33dtxz1SQeIJSMBSmuGHo8ktS/IdfyCfjnYmmFrTKv3+UL30+p5V6jqHkni2Fw4RFGAAAVlA4IGoAAADQAwCdASoMABIAPsFQoUqnpKMhsAgA8BgJbACdMoR3ACre1ssYISAA/ujt5IllRIIyyJNi1KjAzov/NsbRucaI2gu9Pn5Iegynqcj9spTfaY1372Zm2ctt6RzWRiPyaGS9p06OuzwR5gAA',
  },
} satisfies Record<string, ProductImage>

export type ProductImageKey = keyof typeof productImages

/** Returns the full image record, throwing at build time on a bad key. */
export function img(key: ProductImageKey): ProductImage {
  return productImages[key]
}
