/**
 * One-time asset pipeline.
 *
 * The source photography is ~4400x6600px (16MB total) which is far larger than
 * any layout slot needs. This downscales every image to a sensible max edge,
 * re-encodes it as WebP, and emits an `image-data.ts` manifest containing real
 * intrinsic dimensions plus a tiny base64 blur placeholder for each file.
 *
 * Run: node scripts/optimize-images.mjs
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const SRC_DIR = path.join(process.cwd(), 'public/images/original')
const OUT_DIR = path.join(process.cwd(), 'public/images')
const MANIFEST = path.join(process.cwd(), 'lib/image-data.ts')

// Longest edge in CSS pixels * 2 for retina. Nothing in the layout is wider
// than ~1100px, so 2000px is generous and still ~10x smaller than the source.
const MAX_EDGE = 2000

const files = (await readdir(SRC_DIR)).filter((f) => /\.(webp|jpe?g|png)$/i.test(f))
files.sort()

await mkdir(OUT_DIR, { recursive: true })

const entries = []

for (const file of files) {
  const srcPath = path.join(SRC_DIR, file)
  const base = file.replace(/\.[^.]+$/, '')
  const outName = `${base}.webp`
  const outPath = path.join(OUT_DIR, outName)

  const input = sharp(await readFile(srcPath))
  const meta = await input.metadata()

  const pipeline = sharp(await readFile(srcPath))
    .rotate()
    .resize({
      width: meta.width >= meta.height ? MAX_EDGE : undefined,
      height: meta.height > meta.width ? MAX_EDGE : undefined,
      withoutEnlargement: true,
      fit: 'inside',
    })
    .webp({ quality: 82, effort: 6 })

  const buf = await pipeline.toBuffer()
  await writeFile(outPath, buf)

  const outMeta = await sharp(buf).metadata()

  // 12px-wide blurred LQIP, inlined as a data URL for `placeholder="blur"`.
  const blurBuf = await sharp(await readFile(srcPath))
    .rotate()
    .resize(12, null, { fit: 'inside' })
    .blur(1.2)
    .webp({ quality: 55 })
    .toBuffer()

  entries.push({
    key: base,
    src: `/images/${outName}`,
    width: outMeta.width,
    height: outMeta.height,
    blurDataURL: `data:image/webp;base64,${blurBuf.toString('base64')}`,
    bytes: buf.length,
    srcBytes: (await readFile(srcPath)).length,
  })

  const saved = (1 - buf.length / (await readFile(srcPath)).length) * 100
  console.log(
    `${file.padEnd(24)} ${meta.width}x${meta.height} -> ${outMeta.width}x${outMeta.height}  ` +
      `${(buf.length / 1024).toFixed(0)}KB (-${saved.toFixed(0)}%)`,
  )
}

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Intrinsic dimensions + blur placeholders for every product photograph.

export type ProductImage = {
  src: string
  width: number
  height: number
  blurDataURL: string
}

export const productImages = {
${entries
  .map(
    (e) => `  '${e.key}': {
    src: '${e.src}',
    width: ${e.width},
    height: ${e.height},
    blurDataURL:
      '${e.blurDataURL}',
  },`,
  )
  .join('\n')}
} satisfies Record<string, ProductImage>

export type ProductImageKey = keyof typeof productImages

/** Returns the full image record, throwing at build time on a bad key. */
export function img(key: ProductImageKey): ProductImage {
  return productImages[key]
}
`

await writeFile(MANIFEST, ts)

const totalIn = entries.reduce((n, e) => n + e.srcBytes, 0)
const totalOut = entries.reduce((n, e) => n + e.bytes, 0)
console.log(
  `\nTotal: ${(totalIn / 1024 / 1024).toFixed(1)}MB -> ${(totalOut / 1024 / 1024).toFixed(1)}MB`,
)
console.log(`Wrote ${MANIFEST}`)
